[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DASYNCWEBSERVER_REGEX
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  ESP32Async/AsyncTCP@^3.3.2
  ESP32Async/ESPAsyncWebServer@^3.6.0
  adafruit/RTClib@^2.1.4
